<?php
declare(strict_types=1);

return [
    'hero.eyebrow' => 'Mine HOBC from home',
    'hero.title' => 'Start Mining HobbyHash Coin',
    'hero.lead' => 'HOBC mining is SHA-256 solo mining for home miners, nano miners, small test miners, and regular ASICs. This page gives beginners a starting point: get a HOBC address, choose the right pool, enter the miner settings, and understand when payouts happen.',
    'notice.1' => '<strong>Important:</strong> HOBC pools are solo only. Accepted shares show your miner is working, but a payout happens only if your worker finds a real HOBC block. The pool does not split every block reward across all miners.',
    'heading.main_pool_for_asics' => 'Main Pool for ASICs',
    'heading.nano_pool_for_small_miners' => 'Nano Pool for small miners',
    'heading.nano_miner_and_small_miner_setup' => 'Nano Miner and Small Miner Setup',
    'heading.start_here' => 'Start Here',
    'label.1_get_an_address' => '1. Get an address',
    'label.2_pick_a_pool' => '2. Pick a pool',
    'label.3_set_username' => '3. Set username',
    'label.4_set_password' => '4. Set password',
    'label.5_watch_status' => '5. Watch status',
    'heading.what_solo_mining_means' => 'What Solo Mining Means',
    'heading.live_mining_status' => 'Live Mining Status',
    'label.chain_status' => 'Chain status',
    'label.current_height' => 'Current height',
    'label.main_hashrate' => 'Main hashrate',
    'label.main_accepted_shares' => 'Main accepted shares',
    'label.main_rejected_shares' => 'Main rejected shares',
    'label.nano_hashrate' => 'Nano hashrate',
    'label.nano_accepted_shares' => 'Nano accepted shares',
    'label.nano_rejected_shares' => 'Nano rejected shares',
    'heading.common_beginner_questions' => 'Common Beginner Questions',
    'label.can_i_mine_hobc_with_asics' => 'Can I mine HOBC with ASICs?',
    'label.can_small_miners_try' => 'Can small miners try?',
    'label.does_the_pool_split_rewards' => 'Does the pool split rewards?',
    'label.can_i_use_a_btc_address' => 'Can I use a BTC address?',
    'label.is_mining_guaranteed_income' => 'Is mining guaranteed income?',
    'label.metric.asic_miners' => 'ASIC miners',
    'label.metric.small_miners' => 'Small miners',
    'label.password' => 'Password',
    'button.copy_url' => 'Copy URL',
    'value.1_get_an_address' => 'Use a local HOBC wallet, or the custodial web wallet for small balances.',
    'value.2_pick_a_pool' => 'Main Pool for ASICs, Nano Pool for tiny miners.',
    'value.3_set_username' => 'YOUR_HOBC_ADDRESS.worker1',
    'value.4_set_password' => 'x',
    'value.5_watch_status' => 'Use pool pages and stats for real data only.',
    'answer.can_i_mine_hobc_with_asics' => 'Yes, use SHA-256 ASICs on the Main Pool.',
    'answer.can_small_miners_try' => 'Yes, use the Nano Pool at difficulty 0.005.',
    'answer.does_the_pool_split_rewards' => 'No. HOBC pools are solo only.',
    'answer.can_i_use_a_btc_address' => 'No. Use a real HOBC address only.',
    'answer.is_mining_guaranteed_income' => 'No. Payouts happen only when your worker finds a block.',
];
