<?php
declare(strict_types=1);

return [
    'hero.eyebrow' => 'Legal',
    'hero.title' => 'Terms',
    'hero.lead' => 'Rules, notices, and risk disclosures for using the HOBC command center, pools, explorer, support system, SMS program, and custodial web wallet.',
    'section.agreement_to_these_terms.title' => 'Agreement To These Terms',
    'section.agreement_to_these_terms.p1' => 'These Terms apply to HobbyHash Coin, HOBC, hobbyhashcoin.com, the HOBC command center, public website pages, support forms, mining and pool information pages, explorer/status pages, launch reserve pages, burn tracker pages, the custodial web wallet, email notices, and SMS security messages.',
    'section.agreement_to_these_terms.p2' => 'By using the website, creating an account, using the wallet, opening a support ticket, using pool information, or enabling SMS/email security features, you agree to these Terms. If you do not agree, do not use the services.',
    'section.use_at_your_own_risk.title' => 'Use At Your Own Risk',
    'section.use_at_your_own_risk.p1' => 'HOBC services are provided for informational, mining, wallet, and support purposes. Cryptocurrency mining and wallet use involve risk, including software bugs, chain reorganizations, account compromise, lost access, and service interruptions.',
    'section.use_at_your_own_risk.p2' => 'You are responsible for understanding the risks of cryptocurrency, mining, custodial wallets, withdrawals, addresses, transaction confirmations, fees, and blockchain finality. Transactions may be irreversible.',
    'section.no_financial_advice.title' => 'No Financial Advice',
    'section.no_financial_advice.p1' => 'HOBC website content is not financial, investment, legal, or tax advice. The site must not show fake market price, fake market cap, fake blocks, fake txids, fake balances, fake burns, or fake pool stats.',
    'section.no_financial_advice.p2' => 'No website page, statistic, pool page, reserve page, burn page, explorer page, support reply, or wallet status should be treated as a promise of value, profit, mining return, liquidity, exchange listing, or future performance.',
    'section.accounts_and_security.title' => 'Accounts And Security',
    'section.accounts_and_security.p1' => 'You are responsible for keeping your username, email account, password, device, browser, session, and verification codes secure. Do not share passwords or SMS codes. HOBC may use rate limits, CSRF protection, audit logs, SMS codes, email notices, and admin review to protect accounts and wallet funds.',
    'section.accounts_and_security.p2' => 'HOBC may refuse, suspend, limit, or close access when needed to protect the service, investigate abuse, comply with law, respond to suspicious activity, or protect wallet funds.',
    'section.accounts_and_security.p3' => 'HOBC may refuse, suspend, limit, or close access when needed to protect the service, investigate abuse, comply with law, respond to suspicious activity, or protect wallet funds.',
    'section.custodial_wallet_terms.title' => 'Custodial Wallet Terms',
    'section.custodial_wallet_terms.p1' => 'The HOBC web wallet is custodial. The website controls wallet keys and funds until withdrawal. Use a local wallet for larger balances. You are responsible for protecting your login credentials and verification codes.',
    'section.custodial_wallet_terms.p2' => 'Wallet balances, deposits, withdrawals, txids, confirmations, and internal ledger entries must come from real backend and blockchain data. If wallet backend data is offline, syncing, pending, or unavailable, the website should say so instead of showing fake information.',
    'section.custodial_wallet_terms.p3' => 'Deposits may require confirmations before crediting. Withdrawals may be paused, throttled, reviewed, delayed, rejected, refunded internally, queued for broadcast, or require admin approval based on site settings, wallet health, security checks, available hot-wallet funds, or maintenance needs.',
    'section.custodial_wallet_terms.p4' => 'You are responsible for entering the correct withdrawal address. Sending funds to the wrong address may result in permanent loss. The web wallet should not be used for large or long-term balances.',
    'section.sms_program_terms.title' => 'SMS Program Terms',
    'section.sms_program_terms.p1' => '<strong>Program name:</strong> HobbyHash Coin (HOBC) Account Security SMS.',
    'section.sms_program_terms.p2' => '<strong>Program description:</strong> HOBC may send transactional SMS messages for registration verification, login verification, password recovery, admin verification, wallet security, withdrawal verification, support ticket notices, account safety alerts, and related service messages. These messages are not marketing messages.',
    'section.sms_program_terms.p3' => '<strong>Message frequency:</strong> Message frequency varies based on login attempts, verification requests, support activity, wallet security events, and account actions.',
    'section.sms_program_terms.p4' => '<strong>Message and data rates:</strong> Message and data rates may apply.',
    'section.sms_program_terms.p5' => '<strong>Opt-out instructions:</strong> Reply <strong>STOP</strong> to opt out of SMS messages. After opting out, you may not receive SMS login or security codes, which may limit access to protected account or admin features.',
    'section.sms_program_terms.p6' => '<strong>Help instructions:</strong> Reply <strong>HELP</strong> for help, or contact HOBC support at <a href="/contact/?section=SMS%20Support">/contact/?section=SMS Support</a>.',
    'section.sms_program_terms.p7' => '<strong>Support contact:</strong> Open a support ticket at <a href="/contact/?section=SMS%20Support">https://hobbyhashcoin.com/contact/?section=SMS Support</a>.',
    'section.sms_program_terms.p8' => 'SMS opt-in data and phone numbers are not sold, rented, or shared with third parties for marketing or promotional purposes.',
    'section.mining_and_pool_use.title' => 'Mining And Pool Use',
    'section.mining_and_pool_use.p1' => 'HOBC pools are intended for solo mining. Payouts, shares, workers, and block results must come from real pool and chain data. Availability can change during launch, maintenance, or service issues.',
    'section.mining_and_pool_use.p2' => 'Main Pool and Nano Pool information is provided to help miners configure hardware. Solo mining means payouts occur only when a miner finds a real block under the pool rules. Worker counts, hashrate, shares, pool last block, and pool last share must not be faked.',
    'section.mining_and_pool_use.p3' => 'You are responsible for your mining hardware, electricity use, network access, configuration, wallet address, worker name, payout address, and compliance with local rules.',
    'section.explorer_stats_reserve_and_burn_data.title' => 'Explorer, Stats, Reserve, And Burn Data',
    'section.explorer_stats_reserve_and_burn_data.p1' => 'Explorer, stats, reserve, and burn pages are informational tools. They may be syncing, offline, pending launch, or not available. HOBC should not display fake blocks, fake txids, fake addresses, fake supply, fake burns, fake reserve balances, fake market prices, or fake market caps.',
    'section.explorer_stats_reserve_and_burn_data.p2' => 'Launch reserve and burn tracker pages are transparency tools. Current balances and outgoing transactions should be shown only when real tracking data is available.',
    'section.availability_and_maintenance.title' => 'Availability And Maintenance',
    'section.availability_and_maintenance.p1' => 'HOBC may operate in pre-launch, maintenance, or full launch mode. Features may be unavailable, paused, limited, delayed, offline, or changed without notice. Admin pages, wallet backend, node RPC, explorer indexing, pool status, email, SMS, and support tools may have outages or maintenance windows.',
    'section.availability_and_maintenance.p2' => 'Privacy Policy and Terms pages are intended to remain publicly available even when public site status modes limit normal website access.',
    'section.prohibited_uses.title' => 'Prohibited Uses',
    'section.prohibited_uses.p1' => 'Do not use HOBC services to attack the website, bypass security, abuse support, submit malicious content, exploit bugs, launder funds, violate law, impersonate others, interfere with mining or wallet operations, scrape protected data, or attempt unauthorized admin access.',
    'section.prohibited_uses.p2' => 'Do not submit private keys, seed phrases, passwords, API secrets, or sensitive credentials through support tickets or public forms.',
    'section.support_and_abuse.title' => 'Support And Abuse',
    'section.support_and_abuse.p1' => 'Do not submit private keys, seed phrases, passwords, API secrets, or abusive content through support forms. HOBC may log IP addresses, browser details, account details, and admin actions for security and abuse prevention.',
    'section.support_and_abuse.p2' => 'Support replies are informational and do not guarantee any outcome, payout, reversal, listing, balance change, or recovery.',
    'section.third_party_services.title' => 'Third-Party Services',
    'section.third_party_services.p1' => 'HOBC may use third-party services for hosting, SMS delivery, email delivery, security, infrastructure, or other operations. Third-party networks, carriers, wallets, miners, exchanges, browsers, or service providers may have their own terms and limitations.',
    'section.disclaimers_and_limitation_of_liability.title' => 'Disclaimers And Limitation Of Liability',
    'section.disclaimers_and_limitation_of_liability.p1' => 'HOBC services are provided as available and as is. HOBC does not guarantee uninterrupted service, error-free operation, mining results, wallet availability, message delivery, explorer sync, node uptime, pool uptime, market value, or future development.',
    'section.disclaimers_and_limitation_of_liability.p2' => 'To the fullest extent allowed by law, HOBC is not liable for indirect, incidental, special, consequential, or punitive damages, lost profits, lost mining rewards, lost data, lost access, lost funds caused by user error, wrong addresses, compromised credentials, service outages, carrier filtering, blockchain behavior, or third-party services.',
    'section.changes_to_these_terms.title' => 'Changes To These Terms',
    'section.changes_to_these_terms.p1' => 'HOBC may update these Terms as the website, pools, node tools, explorer, wallet, support system, SMS security, launch reserve tracking, and burn tracking change. The updated version will be posted on this page.',
    'section.contact.title' => 'Contact',
    'section.contact.p1' => 'For questions about these Terms, open a support ticket and choose the section that best matches your request.',
    'section.contact.link1' => 'Open Terms Ticket',
    'section.contact.link2' => 'Read Privacy Policy',
];
